### ISSUE TITLE
fix new motion block in motion blocks

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2528]
if a new block is created and added to the agenda, and then it is explicitely stated that it has no parent-element the following error occurs:
_Fehler: data.agenda_parent_id must be bigger than or equal to 1_

**How to recreate:**

1. navigate into motion > motion blocks
2. start adding a new motion block
3. while in the adding dialog add it to agenda 
4. on the field "parent agenda item" select the empty line to indicate nothing as a parent element
5. save the new block
6. the new block is not saved and the Error occurs: data.agenda_parent_id must be bigger than or equal to 1

**wanted behaviour:**
the motion block should be addable to the agenda with explicitely sying that is has not parent element

**Comment by jsangmeister** [comment]
This is due to the fact that the `base-search-selector` uses `0` for its empty element: https://github.com/OpenSlides/openslides-client/blob/128bb684abfacd2063849ba524a1bddbb7162f9e/client/src/app/ui/modules/search-selector/components/base-search-selector/base-search-selector.component.ts#L218

This has been the source of some errors over time. Optimally, it is fixed directly at the source, so other components using this component do not use wrong data.

**Comment by MSoeb** [comment]
Problem can't be verified. Please check again @Elblinator

**Comment by Elblinator** [comment]
I updated the recreation description
The issue is still present

**Comment by reiterl** [comment]
Setting id from 0 to null is not a solution.
